language: go
sudo: required
go:
  - 1.6.2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-software-properties
  - sudo apt-add-repository -y ppa:mosquitto-dev/mosquitto-ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y mosquitto
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck

script:
  - make test

before_deploy:
  - sudo apt-get install -y python-pip
  - sudo pip install -r requirements.txt
  - mkdocs build

  - GOOS=linux GOARCH=amd64 make package
  - GOOS=linux GOARCH=386 make package
  - GOOS=linux GOARCH=arm make package
  - GOOS=darwin GOARCH=amd64 make package
  - GOOS=windows BINEXT=.exe GOARCH=386 make package
  - GOOS=windows BINEXT=.exe GOARCH=amd64 make package

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIOU53PLXIUE7YBBQ
  secret_access_key:
    secure: icpQ0132LlnZD6b2m8o/Bhe9JJnuSJh9hDv1OCmS+h4xO1DSfn1hNuk05a6oyDSwPF04HCbmncTLDcGLnbokK+dL2mrlT6M3BCbC29orLcP7rrUKnq5VLCrVI2jdyBAtLmzNIzPYci8dVuJfj9Voom4/BXosxM+2ry2xa0uvl5dYtzQS7yoocxpl7j3LfzP3hM6GEx64ePIikdOC9U6f1wtdMJ/GjDOUOEl4KqRXYcbOKvufXg+HW3BKLskZsFFn2xoUNvG6rMQZGmirJpiKN+GinEW06HmLEKqynsAMEJEoUw4L40kPhLmT2rm3kUbAQU99ZEitBPmAmh9jA85f6bO1kOVYF9J5S7EVIDUCbqCpaIDoG4w5iVNodb/7VHM5j+6SVjnHHNTpZ3LIF6GD4W6775DzZECU6vZELHymy4ro0haMYRcU3xp+rD/OT1LE031lZK8VcakpyJKb8d2/JO8r22SLBqOI7qV96rhtHSzPxdG4Dug3jXr8Cio/mfHVJOZu9WU37xWhPhjRLPta6AIQAbG+AySptCu/3mqq3uKUFsP9YZQYkCgr4kR7H3hMlvYOVSwmhcQReHuFLN5DotoHFA2f2CgVh1uVaSGoNKDDMK8Zf8ArOslGhRzZrSGRYuxKqbWdae9EIhWyPR4cdnzT11C5/Kdfdj9CqQPgvb0=
  bucket: docs.loraserver.io
  local-dir: site
  upload-dir: lora-semtech-bridge
  acl: public_read
  region: eu-west-1
  on:
    repo: brocaar/lora-semtech-bridge
    branch: docs